Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-10, with the labels that each got.

#247 Fix: Made headings clickable
  js/views/headingView.js
  templates/article.hbs
  templates/block.hbs
  templates/header.jsx
  templates/heading.hbs
  templates/page.hbs
  templates/partials/component.hbs
Labels: bug, accessibility

#223 Fix: Expanded feedback to add images and more control (fixes #222)
  js/helpers.js
  js/models/itemsQuestionModel.js
  js/models/questionModel.js
  less/core/notify.less
  templates/notifyPopup.hbs
Labels: enhancement

#251 Fix: Core cannot find parent on language change triggered by trickle
  js/data.js
  js/models/adaptModel.js
Labels: bug
