Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-07, with the labels that each got.

#159 Append subview rather than prepend
  README.md
  js/views/notifyPopupView.js
  package.json
Labels: accessibility

#133 Convert image.jsx divs to spans
  templates/image.jsx
Labels: bug

#135 Convert drawer button divs to spans
  less/core/drawerItem.less
  templates/drawer.hbs
  templates/drawerItem.hbs
Labels: bug

#141 Converted notify button divs to spans
  templates/notifyPopup.hbs
  templates/notifyPush.hbs
Labels: bug

#146 issue/145 Automated aria levels
  js/a11y.js
  js/helpers.js
  templates/heading.hbs
Labels: enhancement, accessibility

#170 issue/169 router.navigateToElement jquery object fix
  js/router.js
Labels: bug

#161 Add _friendlyId field
  schema/content.schema.json
Labels: enhancement

#153 issue/3311 Removed unnecessary type attribute on script tags
  required/index.html
Labels: bug

#164 issue/123 Moved skip navigation button onscreen
  less/core/nav.less
Labels: bug

#168 Fix: Adding semantic-release package and requirements to the project [#167]
  .github/pull_request_template.md
  .github/workflows/releases.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#155 Added browser support override ability to course config ('targets')
  schema/config.model.schema
  schema/config.schema.json
Labels: enhancement

#148 issue/119 Introduced better loading failure warnings
  js/components.js
  js/data.js
  js/models/configModel.js
  js/views/contentObjectView.js
Labels: enhancement

#163 Update _ariaLevels to use relative strings
  schema/config.schema.json
Labels: enhancement
