Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-09, with the labels that each got.

#228 New: Extended findRelativeModel (fixes #227)
  js/adapt.js
  js/models/adaptModel.js
Labels: enhancement

#226 Fix: NVDA reads clickable (fixes #225)
  js/views/adaptView.js
Labels: bug

#205 Update: _isPartlyCorrect and questionView:submitted (fixes #196)
  js/models/questionModel.js
  js/views/questionView.js
Labels: enhancement

#204 Fix: aria-expanded state to drawer button (fixes #103)
  js/views/drawerView.js
  templates/nav.hbs
Labels: bug, accessibility

#206 Update: Adds context to status indicators (fixes #151)
  templates/heading.hbs
Labels: enhancement, accessibility

#182 New: Added accessible alert api (fixes #181)
  js/views/notifyPushView.js
  js/views/notifyView.js
  templates/notify.hbs
Labels: enhancement, accessibility

#203 Fix: replace deprecated a11y_attrs_heading usage (fixes #202)
  templates/notifyPopup.hbs
  templates/notifyPush.hbs
Labels: enhancement, accessibility

#230 Fix: Automated aria-levels bug (fixes #229)
  js/a11y.js
  js/helpers.js
Labels: bug, high priority

#232 Fix: Update _ariaLevels defaults to use relative strings (fixes #162)
  schema/config.model.schema
Labels: bug

#234 Fix: aria-level is set to "0" for headings (fixes #233)
  js/a11y.js
Labels: bug, accessibility
