Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-06, with the labels that each got.

#118 issue/117 Added _shouldStoreAttempts
  js/models/componentModel.js
  js/models/questionModel.js
Labels: enhancement

#111 issue/110 Added offlineStorage.clear
  js/data.js
  js/offlineStorage.js
Labels: enhancement

#105 issue/104 Added toggleTabbableDescendants
  js/a11y.js
Labels: enhancement, accessibility

#128 issue/122 Fix orientation reporting
  js/device.js
Labels: bug

#129 issue/101 Reverses focus order of drawer holder & header
  templates/drawer.hbs
Labels: bug

#138 issue/3305 Support for alternative course folder name
  js/data.js
Labels: enhancement

#131 issue/130 Filter _isTracking === false from trackingPosition API
  js/data.js
  js/models/adaptModel.js
Labels: bug

#127 issue/126 Fixes notify accessibility blocking
  js/views/notifyPopupView.js
Labels: bug

#152 Adjusts context between header & status in aria-labels
  templates/heading.hbs
Labels: enhancement, accessibility

#147 issue/99 Removed unnecessary labelledby on main region
  js/views/contentObjectView.js
Labels: bug, accessibility
