Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-08, with the labels that each got.

#211 Fix: Add _shouldRenderId to notify api (fixes #208)
  js/views/notifyPopupView.js
  js/views/notifyView.js
Labels: bug

#210 Fix: Device resize html classes rendering speed (fixes #209)
  js/device.js
Labels: bug

#214 Refactored branch issue/193
  js/drawer.js
  js/tooltips.js
  js/views/TooltipView.js
  less/core/tooltip.less
  schema/course.model.schema
  templates/tooltip.jsx
Labels: enhancement

#176 New: `--adapt-viewport-height` to aid viewport height positioning (fixes #175)
  js/device.js
  less/_defaults/_variables.less
Labels: enhancement

#201 Update: provide alternative heading for AT (fixes #173)
  js/models/questionModel.js
  templates/notifyPopup.hbs
Labels: enhancement, accessibility

#221 Update: Remove tabindex from a11y.toggleEnabled (fixes #220)
  js/a11y.js
Labels: accessibility
