Repository adaptlearning/adapt-contrib-core, pull requests merged in 2022-12, with the labels that each got.

#255 Fix: Reset _byAdaptID on load manifest files (fixes #253)
  js/data.js
Labels: bug

#166 New: Added bottom navigation settings (fixes #165)
  js/navigation.js
  less/core/nav.less
  schema/course.model.schema
  schema/course.schema.json
Labels: enhancement

#271 Fix: helper() function in reactHelpers (fixes #270)
  js/reactHelpers.js
Labels: bug

#252 Fix: Corrected check for jsx template (fixes #224)
  js/views/contentObjectView.js
Labels: bug

#274 Update: Updated focus to focus-visible (fixes #231)
  less/core/nav.less
Labels: enhancement

#277 Fix: Error in deprecated logging for drawer (#276)
  js/deprecated.js
Labels: bug

#239 Fix: Navigation button read order (fixes #238)
  js/views/navigationView.js
  less/core/nav.less
  schema/course.model.schema
  schema/course.schema.json
  templates/nav.hbs
Labels: bug, accessibility
