Repository adaptlearning/adapt-contrib-core, pull requests merged in 2023-04, with the labels that each got.

#333 Fix: Allow a small delay between initial click focus and subsequent action
  js/.DS_Store
  js/a11y.js
  js/a11y/browserFocus.js
Labels: bug, accessibility

#342 Fix: Feedback incorrect not final should use fallback
  js/models/questionModel.js
Labels: bug

#347 Fix: Removed locking model error on defaults set
  js/models/lockingModel.js
Labels: bug

#351 Fix: Safari label click for input
  js/fixes.js
  js/fixes/safari.label.click.blur.js
Labels: bug, high priority

#348 New: Added is-prefers-reduced-motion html class and _isPrefersReducedMotionEnabled a11y option
  js/a11y.js
  js/a11y/browserConfig.js
Labels: enhancement, accessibility

#354 Fix: Safari fix invalid AAT ids (fixes #353)
  js/fixes/safari.label.click.blur.js
Labels: bug, high priority, accessibility

#343 Update: Added change vs initial language selection attribute
  js/data.js
Labels: enhancement

#344 Fix: ChildView API broken
  js/views/adaptView.js
Labels: bug

#357 Fix: Ensure marking appears only when canShowMarking is enabled
  js/views/buttonsView.js
Labels: bug

#207 New: added tooltip API (fixes: #193)
  js/a11y.js
  js/a11y/browserFocus.js
  js/app.js
  js/drawer.js
  js/models/TooltipItemModel.js
  js/tooltips.js
  js/views/TooltipItemView.js
  js/views/TooltipView.js
  js/views/navigationView.js
  less/core/tooltip.less
  schema/course.model.schema
  schema/course.schema.json
  templates/nav.hbs
  templates/tooltip.jsx
Labels: enhancement
