Repository adaptlearning/adapt-contrib-core, pull requests merged in 2023-03, with the labels that each got.

#315 Fix: Add header template support for extensions (fixes: #314)
  js/views/headingView.js
  templates/header.jsx
Labels: bug

#311 Fix: Correct appllication of fallback values for feedback title
  js/models/questionModel.js
Labels: bug

#313 Fix: Set drawer position on multi-extension button menu view
  js/views/drawerView.js
Labels: bug

#293 Fix: Switch to native js in isReadable visibility detection
  js/a11y.js
Labels: bug, accessibility

#324 Fix: questionModel.js syntax (fixes: #323)
  js/models/questionModel.js
Labels: bug, high priority

#329 New: Add icon span to instruction element in header.jsx (fixes #328)
  templates/header.jsx
  templates/partials/component.hbs
Labels: enhancement, accessibility

#332 Fix: Removing 'skip-ci' element of commit message for semantic release tags
  package.json
Labels: bug

#309 New: Allow up, down, home, end, pageUp and pageDown to scroll popups (fixes #307)
  js/a11y.js
  js/a11y/popup.js
  js/a11y/scroll.js
Labels: enhancement

#316 New: Update tracking logic to account for Scoring API
  js/tracking.js
  schema/config.model.schema
  schema/config.schema.json
Labels: enhancement
