Repository adaptlearning/adapt-contrib-core, pull requests merged in 2023-10, with the labels that each got.

#451 Fix: Notify popup - Compile _graphic.attribution (fixes #450)
  templates/notifyPopup.hbs
Labels: enhancement

#452 Update: Added content container element (fixes #449)
  templates/page.hbs
Labels: enhancement

#455 Fix: Boolean _isAtLeastOneCorrectSelection (fixes #454)
  js/models/itemsQuestionModel.js
Labels: bug

#458 Fix: Added _isPartlyCorrect to storage mechanism (fixes #457)
  js/models/questionModel.js
Labels: bug

#460 Fix: Add _isA11yCompletionDescriptionEnabled to schema and remove legacy _disableAccessibilityState (fixes #246)
  schema/article.model.schema
  schema/block.model.schema
  schema/component.model.schema
  schema/component.schema.json
  schema/content.schema.json
  schema/contentobject.model.schema
  schema/course.model.schema
  templates/header.jsx
Labels: bug, accessibility
