Repository adaptlearning/adapt-contrib-core, pull requests merged in 2023-08, with the labels that each got.

#421 Further refactor
  js/models/questionModel.js
Labels: bug

#398 New: Added new _srcFocalPoint class to image.jsx (fixes #396)
  templates/image.jsx
Labels: enhancement

#428 Fix: remove component diplayTitle and Title fallbacks for feedbackTitle
  js/models/questionModel.js
Labels: bug, accessibility

#413 Fix: trickle incorrectly unlocking when switching languages
  js/startController.js
Labels: bug

#427 Fix: onAdaptPreInitialize updated to only run on initial load (#426)
  js/views/TooltipView.js
Labels: bug
