Repository adaptlearning/adapt-contrib-core, pull requests merged in 2023-09, with the labels that each got.

#441 Fix: Core version added to automatic framework release (#440)
  .github/workflows/frameworkpullrequest.yml
Labels: bug

#437 Fix: ENUM refactor, linting and fix aliases (fixes #436)
  libraries/enum.js
Labels: bug

#432 Fix: focusFirst on document.body when navigating to a contentObject (#431)
  js/router.js
Labels: bug, accessibility

#438 Update: Added NOT ATTEMPTED enum to COMPLETION_STATE (fixes #424)
  js/enums/completionStateEnum.js
Labels: enhancement

#445 Fix: Drawer Back button position when using an RTL language (fixes #444)
  less/core/drawer.less
Labels: bug
