Repository adaptlearning/adapt-contrib-core, pull requests merged in 2024-06, with the labels that each got.

#550 New: Allow for instance template overrides (fixes #549)
  js/views/adaptView.js
Labels: enhancement

#552 Fix: Show static tooltips at end of event loop always
  js/views/TooltipView.js
Labels: bug

#551 Fix: Resolve title/altTitle discrepancy (fixes #535)
  js/models/questionModel.js
Labels: bug

#554 New: aria label added for partly correct answers (fixes #553)
  js/views/buttonsView.js
Labels: enhancement, accessibility

#548 Fix: Include explicitly set ariaLevel (fixes #547)
  js/a11y.js
Labels: bug

#557 Update: Flag when routing isPreviewMode and reusing common functionality
  js/router.js
Labels: enhancement
