Repository adaptlearning/adapt-contrib-core, pull requests merged in 2024-10, with the labels that each got.

#577 Update: jquery.resize.js to use ResizeObserver
  libraries/jquery.resize.js
Labels: enhancement

#579 Update: inview.js to use IntersectionObserver
  js/views/contentObjectView.js
  js/views/notifyPopupView.js
  libraries/inview.js
Labels: enhancement

#585 New: _isLocked becomes a lockable attribute
  js/models/adaptModel.js
  js/models/lockingModel.js
  js/models/questionModel.js
Labels: enhancement

#589 Fix: Inview locking and triggering (fixes #588)
  libraries/inview.js
Labels: bug

#587 Update: Move notify title above body text (fix #586)
  less/core/notify.less
  templates/notifyPopup.hbs
Labels: enhancement, question

#593 New: Added toggleClass to AdaptModel and ItemModel
  js/modelHelpers.js
  js/models/adaptModel.js
  js/models/itemModel.js
Labels: enhancement

#595 New: Add "has-error" class for use with question components (fixes #594)
  js/views/questionView.js
Labels: enhancement

#597 Fix: inview reprocess on window resize (fixes #596)
  libraries/inview.js
Labels: bug, high priority
