Repository adaptlearning/adapt-contrib-core, pull requests merged in 2025-05, with the labels that each got.

#654 Fix: Add html class to html element (fixes #653)
  less/core/nav.less
  less/core/scrolling.less
  required/index.html
Labels: bug

#636 Fix: add scroll padding to body to avoid focus obscured issue (fixes #635
  less/core/accessibility.less
Labels: bug, ready to release

#652 New: core migration scripts added (fixes #634)
  migrations/v2.js
  migrations/v3.js
  migrations/v4.js
  migrations/v5.js
  migrations/v6.js
Labels: enhancement, high priority, ready to release

#622 New: Use build.timestamp to force json reload
  js/data.js
  required/index.html
Labels: enhancement, ready to release

#655 New: Focus at top of page when routing (fixes #626)
  js/a11y.js
  js/a11y/topOfContentObject.js
  less/core/accessibility.less
  less/core/nav.less
  schema/course.model.schema
  schema/course.schema.json
Labels: enhancement, ready to release

#660 Fix: Fix drawer overflow issue with scrolling(fixes #659)
  less/core/drawer.less
Labels: bug

#663 Update: Replace dialog button aria-expanded with aria-haspopup dialog (fixes #657)
  js/views/drawerView.js
  js/views/navigationView.js
  templates/nav.hbs
Labels: enhancement, accessibility
