Repository adaptlearning/adapt-contrib-core, pull requests merged in 2025-03, with the labels that each got.

#639 Fix: Supplying pluginName on updating menu locking (Fixes #638)
  js/models/menuModel.js
Labels: bug

#649 Fix: Force dialog to close synchronously on page navigation (fixes #648)
  js/drawer.js
  js/views/drawerView.js
Labels: bug, high priority

#633 Fix: trigger `inview` and `onscreen` events when element off screen
  libraries/inview.js
Labels: bug, ready to release
